# generated by datamodel-codegen:
#   filename:  .bundled.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Source(Enum):
    zeek = "zeek"
    suricata = "suricata"


class GraphSnapshotPayload(BaseModel):
    window_start: str = Field(
        ...,
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    window_end: str = Field(
        ...,
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    nodes: list[dict[str, Any]]
    edges: list[dict[str, Any]]
    node_count: int = Field(..., ge=0)
    edge_count: int = Field(..., ge=0)
    contributing_trace_ids: Optional[list[str]] = Field(
        None, pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )


class AnomalousEdge(BaseModel):
    src: str
    dst: str


class DetectionPayload(BaseModel):
    detection_id: str = Field(
        ..., pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    window_start: str = Field(
        ...,
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    window_end: str = Field(
        ...,
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    model_name: str = Field(..., max_length=64, min_length=1)
    model_version: str = Field(..., max_length=32, min_length=1)
    anomalous_nodes: list[str]
    anomalous_edges: list[AnomalousEdge]
    gnn_scores: dict[str, float]
    threshold: float = Field(..., ge=0.0, le=1.0)
    explanation: Optional[dict[str, Any]] = None


class AnalystBriefPayload(BaseModel):
    detection_id: str = Field(
        ..., pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    brief_text: str = Field(..., max_length=4096, min_length=1)
    mitre_technique_id: str = Field(..., pattern="^T[0-9]{4}(\\.[0-9]{3})?$|^T0000$")
    mitre_tactic: str = Field(..., max_length=64, min_length=1)
    mitre_technique_name: Optional[str] = Field(None, max_length=128, min_length=1)
    confidence: float = Field(..., ge=0.0, le=1.0)
    generated_by: str


class Reason(Enum):
    """
    Short machine-readable failure code.
    """

    schema_validation_failed = "schema_validation_failed"
    json_decode_error = "json_decode_error"
    unknown_event_type = "unknown_event_type"
    missing_required_field = "missing_required_field"
    unparseable_timestamp = "unparseable_timestamp"
    unsupported_log_type = "unsupported_log_type"
    internal_error = "internal_error"


class DlqPayload(BaseModel):
    """
    Payload shape for every <topic>.dlq topic. See docs/SCHEMA.md §2.6.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    stage: str = Field(
        ...,
        description="Logical stage that rejected the message, e.g. 'zeek_producer.parse', 'normaliser.schema_validation'.",
        max_length=128,
        pattern="^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$",
    )
    reason: Reason = Field(..., description="Short machine-readable failure code.")
    detail: Optional[str] = Field(
        None, description="Human-readable validator/exception message.", max_length=4096
    )
    raw: str = Field(
        ...,
        description="Original message body. JSON-stringified if it was valid JSON; otherwise base64 bytes prefixed with 'b64:'.",
        min_length=1,
    )


class Port(RootModel[int]):
    root: int = Field(..., ge=0, le=65535)


class Protocol(Enum):
    tcp = "tcp"
    udp = "udp"
    icmp = "icmp"
    other = "other"


class Header(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"] = Field(
        ...,
        description="Frozen at 1.0.0 for the initial freeze. See docs/SCHEMA.md §4 for bump rules.",
    )
    org_id: str = Field(
        ...,
        description="Tenant identifier. Default 'org-000' for single-tenant deployments.",
        pattern="^[a-z0-9][a-z0-9-]{0,63}$",
    )
    event_id: str = Field(
        ...,
        description="Per-message unique ID. UUIDv7 recommended (time-sortable); UUIDv4 accepted.",
        max_length=36,
        min_length=36,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    )
    produced_at: str = Field(
        ...,
        description="RFC3339 UTC timestamp with millisecond precision (trailing 'Z' mandatory).",
        max_length=24,
        min_length=24,
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    producer: str = Field(
        ...,
        description="Producing service identity. Form: '<service-name>/<version>[@<instance>]'.",
        max_length=128,
        min_length=5,
        pattern="^[a-z][a-z0-9_]*\\/[0-9]+\\.[0-9]+\\.[0-9]+(@[a-z0-9][a-z0-9-]{0,63})?$",
    )
    trace_id: str = Field(
        ...,
        description="End-to-end trace identifier. Set once at ingestion, copied forward unchanged through all pipeline stages. See docs/SCHEMA.md §3.",
        max_length=36,
        min_length=36,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    )


class ProcessedEventPayload(BaseModel):
    """
    Canonical, vendor-neutral 5-tuple event derived from a single raw_logs message. See docs/SCHEMA.md §2.2.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ts: str = Field(
        ...,
        description="Canonical event timestamp (RFC3339 UTC ms).",
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    src_ip: str = Field(
        ...,
        max_length=45,
        min_length=3,
        pattern="^([0-9]{1,3}(\\.[0-9]{1,3}){3}|[0-9a-fA-F:]+)$",
    )
    dst_ip: str = Field(
        ...,
        max_length=45,
        min_length=3,
        pattern="^([0-9]{1,3}(\\.[0-9]{1,3}){3}|[0-9a-fA-F:]+)$",
    )
    src_port: Optional[Port] = Field(
        None, description="Null for ICMP or when the source vendor omits it."
    )
    dst_port: Optional[Port] = None
    protocol: Protocol
    bytes_sent: int = Field(
        ..., description="src->dst payload bytes. Zero if unknown.", ge=0
    )
    bytes_recv: int = Field(
        ..., description="dst->src payload bytes. Zero if unknown.", ge=0
    )
    packets_sent: Optional[int] = Field(None, ge=0)
    packets_recv: Optional[int] = Field(None, ge=0)
    duration_ms: Optional[int] = Field(None, ge=0)
    alert_flag: bool = Field(
        ...,
        description="True iff event indicates a flagged condition. Rule: Suricata log_type=='alert' OR Zeek conn_state in {S0,REJ,RSTR,RSTO}.",
    )
    alert_signature: Optional[str] = Field(None, max_length=256)
    alert_category: Optional[str] = Field(None, max_length=128)
    conn_state: Optional[str] = Field(None, max_length=8)
    community_id: Optional[str] = Field(None, max_length=64)
    sensor_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]{0,63}$")
    source: Source


class SuricataRawLog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["suricata"]
    log_type: str = Field(
        ...,
        description="Vendor-native log family. Suricata: 'flow'|'alert'|'dns'|'http'|'tls'|'fileinfo'.",
        max_length=32,
        min_length=1,
    )
    sensor_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]{0,63}$")
    received_at: str = Field(
        ...,
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    raw: dict[str, Any]
    flow_id: Optional[int] = Field(None, ge=0)
    src_ip: str = Field(
        ...,
        description="IPv4 dotted-quad or IPv6 string. Lenient pattern; strict parsing happens in code.",
        max_length=45,
        min_length=3,
        pattern="^([0-9]{1,3}(\\.[0-9]{1,3}){3}|[0-9a-fA-F:]+)$",
    )
    src_port: Optional[Port] = None
    dest_ip: str = Field(
        ...,
        description="IPv4 dotted-quad or IPv6 string. Lenient pattern; strict parsing happens in code.",
        max_length=45,
        min_length=3,
        pattern="^([0-9]{1,3}(\\.[0-9]{1,3}){3}|[0-9a-fA-F:]+)$",
    )
    dest_port: Optional[Port] = None
    proto: Protocol
    community_id: Optional[str] = Field(None, max_length=64)
    bytes_toserver: Optional[int] = Field(None, ge=0)
    bytes_toclient: Optional[int] = Field(None, ge=0)
    pkts_toserver: Optional[int] = Field(None, ge=0)
    pkts_toclient: Optional[int] = Field(None, ge=0)
    alert_signature_id: Optional[int] = Field(None, ge=0)
    alert_signature: Optional[str] = Field(None, max_length=256)
    alert_category: Optional[str] = Field(None, max_length=128)
    alert_severity: Optional[int] = Field(None, ge=1, le=5)


class ZeekRawLog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["zeek"]
    log_type: str = Field(
        ...,
        description="Vendor-native log family. Zeek: 'conn'|'dns'|'http'|'ssl'|...",
        max_length=32,
        min_length=1,
    )
    sensor_id: str = Field(
        ...,
        description="Stable sensor instance identifier.",
        pattern="^[a-z0-9][a-z0-9-]{0,63}$",
    )
    received_at: str = Field(
        ...,
        description="Sensor-side event timestamp, normalised to RFC3339 UTC ms.",
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    )
    raw: dict[str, Any] = Field(
        ..., description="Verbatim vendor row, preserved for forensic replay."
    )
    uid: Optional[str] = Field(None, max_length=64, min_length=1)
    id_orig_h: str = Field(
        ...,
        description="IPv4 dotted-quad or IPv6 string. Lenient pattern; strict parsing happens in code.",
        max_length=45,
        min_length=3,
        pattern="^([0-9]{1,3}(\\.[0-9]{1,3}){3}|[0-9a-fA-F:]+)$",
    )
    id_orig_p: int = Field(..., ge=0, le=65535)
    id_resp_h: str = Field(
        ...,
        description="IPv4 dotted-quad or IPv6 string. Lenient pattern; strict parsing happens in code.",
        max_length=45,
        min_length=3,
        pattern="^([0-9]{1,3}(\\.[0-9]{1,3}){3}|[0-9a-fA-F:]+)$",
    )
    id_resp_p: int = Field(..., ge=0, le=65535)
    proto: Protocol
    service: Optional[str] = Field(None, max_length=32)
    duration: Optional[float] = Field(None, ge=0.0)
    orig_bytes: Optional[int] = Field(None, ge=0)
    resp_bytes: Optional[int] = Field(None, ge=0)
    conn_state: Optional[str] = Field(None, max_length=8)
    history: Optional[str] = Field(None, max_length=64)
    orig_pkts: Optional[int] = Field(None, ge=0)
    resp_pkts: Optional[int] = Field(None, ge=0)
    local_orig: Optional[bool] = None
    local_resp: Optional[bool] = None


class ProcessedEventsMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    payload: ProcessedEventPayload


class GraphSnapshotsMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    payload: GraphSnapshotPayload


class DetectionsMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    payload: DetectionPayload


class AnalystBriefsMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    payload: AnalystBriefPayload


class DlqMessage(BaseModel):
    """
    Schema shared by every <topic>.dlq topic.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    payload: DlqPayload


class RawLogsMessage(BaseModel):
    """
    Full envelope + raw_log payload. This is what producers validate against before send and consumers validate against on receive.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    payload: Union[ZeekRawLog, SuricataRawLog] = Field(
        ...,
        description="Discriminated union of Zeek conn-style records and Suricata eve.json records. Variant is selected on the `source` field. See docs/SCHEMA.md §2.1.",
        title="raw_logs payload",
    )


class SentinelMeshMessage(
    RootModel[
        Union[
            RawLogsMessage,
            ProcessedEventsMessage,
            GraphSnapshotsMessage,
            DetectionsMessage,
            AnalystBriefsMessage,
            DlqMessage,
        ]
    ]
):
    root: Union[
        RawLogsMessage,
        ProcessedEventsMessage,
        GraphSnapshotsMessage,
        DetectionsMessage,
        AnalystBriefsMessage,
        DlqMessage,
    ] = Field(
        ...,
        description="Aggregator schema used solely by the code generators (quicktype, datamodel-code-generator) to produce docs/types.ts and docs/models.py from a single entry point. Not used at runtime for validation; validation uses the per-message schemas under messages/.",
        title="SentinelMesh — all message types",
    )
